name: MultipleBedSpawn
version: '${project.version}'
main: me.gabrielfj.multiplebedspawn.MultipleBedSpawn
api-version: 1.19
load: STARTUP
authors: [ GabrielFJ ]
description: A simple plugin to allow players to choose which bed to respawn into.
website: https://github.com/GabrielFJunkes
commands:
  renamebed:
    description: Change the name of the bed you are looking at
    usage: /<command> "name of the bed"
  removebed:
    description: Opens a menu to remove saved beds
    usage: /<command>
permissions:
  multiplebedspawn.skipcooldown:
    description: Allows the player to skip the bed's respawn cooldown
    default: false
  multiplebedspawn.maxcount.*:
    description: Allows to set custom max number of beds (ignores the config)
    default: false


